site_name: LiZH0911的学习笔记
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - search.suggest
    - content.code.copy

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式

  icon:
    logo: material/book-open-page-variant

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/home.css

nav:
  - 主页: index.md
  - 课程:
    - 首页: course/index.md
    # - 示例: course/example.md
    - Python 基础: course/Python/index.md
    - PythonWeb: course/PythonWeb/index.md
        # - FastAPI: course/PythonWeb/FastAPI/index.md
#    - LangChain: course/LangChain/index.md
    - Java 基础: course/Java/index.md
    - JavaWeb:
        - JavaWeb首页: course/JavaWeb/index.md
        - HTML-CSS: course/JavaWeb/HTML-CSS/index.md
#        - JavaScript: course/JavaWeb/JavaScript/index.md
#        - Vue: course/JavaWeb/Vue/index.md
#        - Ajax: course/JavaWeb/Ajax/index.md
#        - Maven: course/JavaWeb/Maven/index.md
#        - Web基础: course/JavaWeb/Web基础/index.md
#        - MySQL: course/JavaWeb/MySQL/index.md
#        - JDBL: course/JavaWeb/JDBL/index.md
#        - Mybatis: course/JavaWeb/Mybatis/index.md
#        - Docker: course/JavaWeb/Docker/index.md
  - 关于: about/index.md
